name: Check Markdown Links

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 9 * * 1'  # Runs every Monday at 9 AM

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/markdown-link-check-config.json'
